name: Update MPP Dashboard

on:
  schedule:
    - cron: '0 */4 * * *' # S'exécute toutes les 4 heures
  workflow_dispatch: # Permet de lancer manuellement

# Correction pour forcer l'utilisation de Node.js 24 et retirer l'avertissement
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - run: pip install requests
      
      - env:
          MPP_EMAIL: ${{ secrets.MPP_EMAIL }}
          MPP_REFRESH_TOKEN: ${{ secrets.MPP_REFRESH_TOKEN }}
        run: python update_dashboard.py
        
      - uses: actions/configure-pages@v4
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - uses: actions/deploy-pages@v4
